ERROR_ACCESS_DENIED = "ACCESS DENIED"
ERROR_ACCESS_TOKEN_NOT_EXPIRED = "ACCESS TOKEN NOT EXPIRED"
ERROR_ALREADY_LOGOUT = "ALREADY LOGOUT"

ERROR_EXPIRED_SHORT_URL = "EXPIRED SHORT URL"
ERROR_EXPIRED_SIGNATURE = "EXPIRED SIGNATURE"

ERROR_INTEGRITY = "ALREADY REGISTERED"
ERROR_INVAILD_TOKEN = "INVAILD TOKEN"

ERROR_NOT_AN_EMAIL_FORMAT = "NOT AN EMAIL FORMAT"
ERROR_NOT_EXIST_ACCOUNT = "NOT EXIST ACCOUNT"
ERROR_NOT_EXIST_DATA = "NOT EXIST DATA"
ERROR_NOT_YOUR_DATA = "NOT YOUR DATA"

ERROR_OLD_TOKEN = "OLD TOKEN"

ERROR_PASSWORD_MIN_LENGTH = "PASSWORD MUST BE AT LEAST 8 CHARACTERS LONG"

ERROR_SERVER = "SERVER ERROR"

ERROR_WRONG_PASSWORD = "WRONG PASSWORD"
